"""
content_checker.py

This file checks generated content before a human reviews it.

For now, we are checking LinkedIn posts.

Important:
This checker does NOT replace human review.
It only helps us catch obvious problems before posting.
"""


def check_linkedin_post(post: str) -> dict:
    """
    Check whether a LinkedIn post follows basic quality and safety rules.

    Parameters:
        post:
            The LinkedIn post text generated by the LLM.

    Returns:
        A dictionary with:
        - passed: True or False
        - issues: a list of problems found
        - suggestions: a list of recommended edits
    """

    issues = []
    suggestions = []

    # Rule 1: LinkedIn posts should not be longer than 3000 characters.
    if len(post) > 3000:
        issues.append("The post is longer than LinkedIn's 3000 character limit.")
        suggestions.append("Shorten the post before publishing.")

    # Rule 2: Avoid spammy engagement bait.
    # These phrases can make the post feel low-quality or manipulative.
    spammy_phrases = [
        "comment yes",
        "comment below if",
        "like and share",
        "follow me for more",
        "dm me now",
        "don't miss out",
        "limited time only",
    ]

    lower_post = post.lower()

    for phrase in spammy_phrases:
        if phrase in lower_post:
            issues.append(f"Possible spammy phrase found: '{phrase}'")
            suggestions.append("Remove engagement bait and make the post more professional.")

    # Rule 3: Too many hashtags can make the post look less professional.
    hashtag_count = post.count("#")

    if hashtag_count > 5:
        issues.append("The post has too many hashtags.")
        suggestions.append("Use 0-3 relevant hashtags.")

    # Rule 4: Watch for fake-looking statistics.
    # This does not prove the statistic is fake.
    # It only reminds us to verify numbers before posting.
    if "%" in post:
        issues.append("The post includes a percentage or statistic.")
        suggestions.append("Check that any statistic is true and has a reliable source.")

    # Rule 5: Avoid generic AI marketing language.
    generic_ai_phrases = [
        "revolutionize",
        "game-changer",
        "cutting-edge",
        "unlock the power",
        "transform your business",
        "leverage ai",
    ]

    for phrase in generic_ai_phrases:
        if phrase in lower_post:
            issues.append(f"Generic AI phrase found: '{phrase}'")
            suggestions.append("Replace generic AI wording with a more specific insight.")

    # Rule 6: LinkedIn posts often work well when they invite discussion.
    # This is not mandatory, but our template asks for a thoughtful question.
    if "?" not in post:
        issues.append("The post does not include a question.")
        suggestions.append("Consider ending with a thoughtful question for the reader.")

    # If there are no issues, the post passes the automatic check.
    passed = len(issues) == 0

    return {
        "passed": passed,
        "issues": issues,
        "suggestions": suggestions,
    }