"""
llm_integration.py

This file connects our Python project to the LLM API.

It does NOT decide what kind of content to write.
It only receives a finished prompt, sends it to the model,
and gives back the model's answer.
"""

import os
from dotenv import load_dotenv
from openai import OpenAI


# Load secret settings from the .env file.
# This lets us use OPENAI_API_KEY without writing the key inside the code.
load_dotenv()


# Create the OpenAI client.
# The client automatically looks for OPENAI_API_KEY in the environment.
client = OpenAI()


def generate_content(prompt: str) -> str:
    """
    Send a prompt to the LLM and return the generated text.

    Parameters:
        prompt:
            A string containing the full instruction we want to send to the LLM.
            Later, this prompt will come from our prompt_templates.py file.

    Returns:
        A string containing the text generated by the LLM.
    """

    # Read the model name from .env.
    # If OPENAI_MODEL is missing, Python will use "gpt-5" as the default.
    model = os.getenv("OPENAI_MODEL", "gpt-5")

    # Send the prompt to the LLM.
    # input=prompt means: "Here is the task. Please answer it."
    response = client.responses.create(
        model=model,
        input=prompt,
    )

    # response.output_text contains the final text answer from the model.
    return response.output_text