"""
test_content_checker.py

This file tests our LinkedIn post checker.

We are not calling the LLM here.
We are only checking if our rule-based checker can detect problems
inside a LinkedIn-style post.
"""

from content_checker import check_linkedin_post


# This is a sample LinkedIn post for testing.
# You can replace this text with the real post generated by your LLM.
sample_post = """
AI products do not fail only because the model is weak.

They often fail because users do not understand what the system can do,
when to trust it, or how to recover when it makes a mistake.

That is why UX research should happen before launch, not after complaints arrive.

Better AI starts with better questions:
What does the user expect?
Where could the system confuse them?
What decisions need human control?

How early does your team involve UX research in AI product development?
"""


# Run the checker on the sample post.
check_result = check_linkedin_post(sample_post)


# Print the full result.
print(check_result)